const nationalityToCode: Record<string, string> = {
  British: "GB",
  English: "GB",
  Scottish: "GB",
  German: "DE",
  Italian: "IT",
  French: "FR",
  Spanish: "ES",
  Brazilian: "BR",
  Dutch: "NL",
  Finnish: "FI",
  Australian: "AU",
  Austrian: "AT",
  Canadian: "CA",
  American: "US",
  Mexican: "MX",
  Japanese: "JP",
  Chinese: "CN",
  Russian: "RU",
  Swiss: "CH",
  Swedish: "SE",
  Belgian: "BE",
  Danish: "DK",
  Indian: "IN",
  "South African": "ZA",
  Argentine: "AR",
  Colombian: "CO",
  Venezuelan: "VE",
  Polish: "PL",
  Czech: "CZ",
  Hungarian: "HU",
  Portuguese: "PT",
  Irish: "IE",
  "New Zealander": "NZ",
  Indonesian: "ID",
  Malaysian: "MY",
  Thai: "TH",
  Monegasque: "MC",
  Maltese: "MT",
  Chilean: "CL",
  Uruguayan: "UY",
  Rhodesian: "ZW",
  "East German": "DE",
  Czechoslovakian: "CZ",
  Liechtensteiner: "LI",
  Ukrainian: "UA",
  Greek: "GR",
  Romanian: "RO",
  Bulgarian: "BG",
  Turkish: "TR",
  Slovak: "SK",
  Slovenian: "SI",
  Croatian: "HR",
  "South Korean": "KR",
  Vietnamese: "VN",
  Moroccan: "MA",
  Norwegian: "NO",
  Icelandic: "IS",
  Luxembourgish: "LU",
  Lithuanian: "LT",
  Latvian: "LV",
  Estonian: "EE",
  Cypriot: "CY",
  Israeli: "IL",
  Bahraini: "BH",
  Qatari: "QA",
  Emirati: "AE",
  Saudi: "SA",
  Singaporean: "SG",
  Bahrain: "BH",
  "Saudi Arabia": "SA",
  Australia: "AU",
  Azerbaijan: "AZ",
  Spain: "ES",
  Monaco: "MC",
  "United Kingdom": "GB",
  Belgium: "BE",
  Italy: "IT",
  Singapore: "SG",
  Japan: "JP",
  "United Arab Emirates": "AE",
  Brazil: "BR",
  Austria: "AT",
  "United States": "US",
  Qatar: "QA",
  Hungary: "HU",
  Netherlands: "NL",
  China: "CN",
  Portugal: "PT",
  Mexico: "MX",
  Canada: "CA",
  France: "FR",
  Germany: "DE",
  India: "IN",
  "South Africa": "ZA",
  Argentina: "AR",
  Colombia: "CO",
  Venezuela: "VE",
  Poland: "PL",
  "Czech Republic": "CZ",
  Turkey: "TR",
  Russia: "RU",
  Sweden: "SE",
  Switzerland: "CH",
  Denmark: "DK",
  Ireland: "IE",
  "New Zealand": "NZ",
  Indonesia: "ID",
  Malaysia: "MY",
  Thailand: "TH",
  Vietnam: "VN",
  Morocco: "MA",
  Korea: "KR",
  "South Korea": "KR",
  Greece: "GR",
  Romania: "RO",
  Bulgaria: "BG",
  Croatia: "HR",
  Slovenia: "SI",
  Slovakia: "SK",
  Lithuania: "LT",
  Latvia: "LV",
  Estonia: "EE",
  Cyprus: "CY",
  Israel: "IL",
  Ukraine: "UA",
  Norway: "NO",
  Iceland: "IS",
  Luxembourg: "LU",
  "San Marino": "SM",
  Bahamas: "BS",
  Barbados: "BB",
  "East Germany": "DE",
  Rhodesia: "ZW",
  Czechoslovakia: "CZ",
  "Great Britain": "GB",
  UK: "GB",
  USA: "US",
  UAE: "AE",
}

const DEFAULT_SIZE = 64
const DEFAULT_STYLE = "flat"

export function getFlagUrl(
  nationality: string | null | undefined,
  size: number = DEFAULT_SIZE,
  style: string = DEFAULT_STYLE,
): string | null {
  if (!nationality) return null
  const code = nationalityToCode[nationality]
  if (!code) return null
  return `https://flagsapi.com/${code}/${style}/${size}.png`
}

export function getCountryCode(nationality: string): string | null {
  return nationalityToCode[nationality] ?? null
}
